services:
  web:
    build: ./php
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST} client_port=9003"

  node:
    build: ./node
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
