services:
  web:
    build: ./php
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/99-dev.ini:/usr/local/etc/php/conf.d/99-dev.ini
    environment:
      XDEBUG_CONFIG: "client_host=${XDEBUG_CLIENT_HOST} client_port=9003"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  node:
    build: ./node
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: lamp_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_phpmyadmin
    ports:
      - "8060:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  technitium-dns:
    image: technitium/dns-server
    container_name: dns
    ports:
      - "53:53/udp"
      - "5380:5380/tcp"
    volumes:
      - technitium-data:/etc/dns
    environment:
      - DNS_SERVER_ADMIN_PASSWORD=netlab123
    restart: unless-stopped

volumes:
  db_data:
  technitium-data:
